import React from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowRight,
  Bot,
  ChartNoAxesColumn,
  Check,
  Droplets,
  Flame,
  Heart,
  Leaf,
  MessageCircle,
  Moon,
  Ruler,
  Scale,
  Search,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  UtensilsCrossed,
} from '../components/OpenMojiIcons';
import { useTheme } from '../context/ThemeContext';
import BrandLogo from '../components/BrandLogo';

const features = [
  { icon: Bot, title: 'AI Meal Plans', desc: 'Personalized plans generated by Llama AI — tailored to your goals, allergies, and taste.' },
  { icon: ChartNoAxesColumn, title: 'Progress Tracking', desc: 'Log your weight, calories, water, and macros. See your journey visualized in beautiful charts.' },
  { icon: Search, title: 'Food Database', desc: 'Search millions of real foods from Open Food Facts, plus AI fills any gaps instantly.' },
  { icon: MessageCircle, title: 'AI Nutrition Coach', desc: 'Chat with your personal nutrition assistant anytime. Ask anything about diet and health.' },
  { icon: ShoppingCart, title: 'Grocery Lists', desc: 'Auto-generated shopping lists from your meal plan. Never forget an ingredient again.' },
  { icon: Smartphone, title: 'Mobile Friendly', desc: 'Works beautifully on any device — phone, tablet, or desktop with native app feel.' },
];

const steps = [
  { step: '01', title: 'Create your account', desc: 'Sign up free in 30 seconds. Tell us your goals, dietary needs, and preferences.' },
  { step: '02', title: 'Get your meal plan', desc: 'Our AI generates a personalized meal plan based on your profile and budget.' },
  { step: '03', title: 'Track your progress', desc: 'Log meals, weight, and workouts. Watch your progress with beautiful charts.' },
  { step: '04', title: 'Reach your goal', desc: 'Stay on track with AI coaching, reminders, and weekly plan adjustments.' },
];

const plans = [
  {
    name: 'Free',
    price: '₱0',
    priceUSD: '$0',
    period: 'forever',
    badge: 'Free',
    badgeIcon: Leaf,
    color: 'border-sage-200',
    features: [
      '1-day AI meal plans',
      'BMI & calorie calculator',
      'Food database search',
      'Basic progress tracking',
      'Water & meal reminders',
      'Daily diet tips',
    ],
    cta: 'Get Started Free',
    ctaStyle: 'btn-secondary w-full justify-center flex',
    to: '/register',
  },
  {
    name: 'Premium',
    price: '₱199',
    priceUSD: '$3.99',
    period: 'per month',
    badge: 'Premium',
    badgeIcon: Sparkles,
    color: 'border-amber-300 ring-2 ring-amber-200',
    popular: true,
    features: [
      'Everything in Free',
      'Personalized 7-day plans',
      'AI Nutrition Coach chat',
      'Grocery list generation',
      'Meal replacement suggestions',
      'Advanced macro tracking',
      'Budget & region-specific meals',
      'Allergy & diet restriction support',
      'No advertisements',
    ],
    cta: 'Start Premium',
    ctaStyle: 'w-full justify-center flex items-center bg-amber-400 hover:bg-amber-500 text-white font-medium px-5 py-2.5 rounded-xl transition-all duration-200 shadow-sm hover:shadow-md',
    to: '/register',
  },
];

export default function Landing() {
  const { effectiveTheme, toggleTheme, theme } = useTheme();

  const ThemeIcon = effectiveTheme === 'dark' ? Sun : Moon;

  const dashboardStats = [
    { label: 'Daily Calories', value: '1,850', unit: 'kcal', icon: Flame, color: 'text-orange-500' },
    { label: 'Current Weight', value: '72.5', unit: 'kg', icon: Scale, color: 'text-blue-500' },
    { label: 'BMI', value: '23.6', unit: 'Healthy', icon: Ruler, color: 'text-sage-600' },
    { label: 'Water Today', value: '6/8', unit: 'glasses', icon: Droplets, color: 'text-cyan-500' },
  ];

  const quickItems = [
    { icon: UtensilsCrossed, label: 'Meal Plans' },
    { icon: ChartNoAxesColumn, label: 'Progress' },
    { icon: MessageCircle, label: 'AI Chat' },
  ];

  return (
    <div className="min-h-screen bg-cream dark:bg-gray-950 transition-colors duration-200">

      {/* ── NAVBAR ── */}
      <nav className="sticky top-0 z-50 bg-white/80 dark:bg-gray-900/80 backdrop-blur-md border-b border-sage-100 dark:border-gray-800">
        <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <BrandLogo size="sm" className="h-[7.03125rem] w-[7.03125rem]" />
            <span className="font-display text-2xl font-semibold text-sage-900 dark:text-white">heAlthy</span>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={toggleTheme}
              className="w-9 h-9 rounded-xl bg-sage-50 dark:bg-gray-800 flex items-center justify-center hover:bg-sage-100 dark:hover:bg-gray-700 transition-colors"
              title={`Theme: ${theme}`}
            >
              <ThemeIcon className="h-4 w-4" aria-hidden="true" />
            </button>
            <Link to="/login" className="btn-ghost text-sm hidden sm:block">Sign In</Link>
            <Link to="/register" className="btn-primary text-sm py-2 px-4">Get Started Free</Link>
          </div>
        </div>
      </nav>

      {/* ── HERO ── */}
      <section className="max-w-6xl mx-auto px-4 pt-16 pb-20 text-center">
        <div className="animate-fadeIn">
          <span className="inline-flex items-center gap-2 bg-sage-100 dark:bg-sage-900 text-sage-700 dark:text-sage-300 text-sm font-medium px-4 py-1.5 rounded-full mb-6">
            <Bot className="h-4 w-4" aria-hidden="true" />
            Powered by Llama AI — Free Forever
          </span>
          <h1 className="font-display text-5xl md:text-7xl font-bold text-sage-900 dark:text-white leading-tight mb-6">
            Eat Smart,<br />
            <span className="text-sage-600 dark:text-sage-400">Live heAlthy</span>
          </h1>
          <p className="text-lg md:text-xl text-sage-600 dark:text-gray-400 max-w-2xl mx-auto mb-8 leading-relaxed">
            AI-powered personalized meal plans, nutrition coaching, and progress tracking — all in one app. Free forever.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Link to="/register" className="btn-primary text-lg py-4 px-8 inline-flex items-center gap-2">
              <ArrowRight className="h-5 w-5" aria-hidden="true" />
              Start for Free
            </Link>
            <Link to="/login" className="btn-secondary text-lg py-4 px-8 inline-flex items-center gap-2">
              Sign In
              <ArrowRight className="h-5 w-5" aria-hidden="true" />
            </Link>
          </div>
          <p className="text-sm text-sage-400 dark:text-gray-500 mt-4">No credit card required · Free forever</p>
        </div>

        {/* App preview mockup */}
        <div className="mt-16 animate-slideUp" style={{ animationDelay: '0.2s', opacity: 0, animationFillMode: 'forwards' }}>
          <div className="relative max-w-4xl mx-auto">
            {/* Glow effect */}
            <div className="absolute inset-0 bg-gradient-to-r from-sage-400/20 to-amber-400/20 blur-3xl rounded-3xl" />
            {/* Dashboard preview card */}
            <div className="relative bg-sage-50 dark:bg-gray-900 rounded-3xl shadow-2xl border border-sage-100 dark:border-gray-800 overflow-hidden">
              {/* Fake browser bar */}
              <div className="bg-sage-50 dark:bg-gray-800 px-4 py-3 flex items-center gap-2 border-b border-sage-100 dark:border-gray-700">
                <div className="flex gap-1.5">
                  <div className="w-3 h-3 rounded-full bg-red-400" />
                  <div className="w-3 h-3 rounded-full bg-amber-400" />
                  <div className="w-3 h-3 rounded-full bg-green-400" />
                </div>
                <div className="flex-1 bg-white dark:bg-gray-700 rounded-lg px-3 py-1 text-xs text-sage-400 dark:text-gray-400 max-w-xs mx-auto text-center">
                  healthy-app.vercel.app
                </div>
              </div>
              {/* Dashboard content preview */}
              <div className="p-6 grid grid-cols-2 md:grid-cols-4 gap-3">
                {dashboardStats.map((stat) => (
                  <div key={stat.label} className="bg-sage-50 dark:bg-gray-800 rounded-xl p-3 text-left">
                    <stat.icon className="h-5 w-5 md:h-6 md:w-6 text-sage-600 dark:text-sage-300" aria-hidden="true" />
                    <p className={`text-xl font-display font-bold mt-1 ${stat.color}`}>{stat.value}</p>
                    <p className="text-xs text-sage-400 dark:text-gray-500">{stat.unit}</p>
                    <p className="text-xs font-medium text-sage-600 dark:text-gray-400 mt-0.5">{stat.label}</p>
                  </div>
                ))}
              </div>
              <div className="px-6 pb-6 grid grid-cols-3 gap-3">
                {quickItems.map((item) => (
                  <div key={item.label} className="bg-gradient-to-br from-sage-600 to-sage-700 text-white rounded-xl p-3 text-center text-sm font-medium shadow-sm inline-flex items-center justify-center gap-1.5 md:gap-2">
                    <item.icon className="h-4 w-4 md:h-5 md:w-5" aria-hidden="true" />
                    {item.label}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section className="bg-white dark:bg-gray-900 py-20 border-y border-sage-100 dark:border-gray-800">
        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="font-display text-4xl font-bold text-sage-900 dark:text-white mb-3">
              Everything you need
            </h2>
            <p className="text-sage-600 dark:text-gray-400 text-lg max-w-xl mx-auto">
              A complete nutrition toolkit powered by AI — all free, no subscriptions needed for the basics.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 stagger-children">
            {features.map((f) => (
              <div key={f.title} className="p-6 rounded-2xl border border-sage-100 dark:border-gray-800 bg-sage-50/50 dark:bg-gray-800/50 hover:border-sage-300 dark:hover:border-gray-600 transition-all duration-200 hover:shadow-md">
                <f.icon className="h-7 w-7 block mb-3 text-sage-600 dark:text-sage-300" aria-hidden="true" />
                <h3 className="font-display text-lg font-semibold text-sage-900 dark:text-white mb-2">{f.title}</h3>
                <p className="text-sage-600 dark:text-gray-400 text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS ── */}
      <section className="py-20 max-w-6xl mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="font-display text-4xl font-bold text-sage-900 dark:text-white mb-3">
            How it works
          </h2>
          <p className="text-sage-600 dark:text-gray-400 text-lg">Get started in minutes, see results in weeks</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 stagger-children">
          {steps.map((s, i) => (
            <div key={s.step} className="relative text-center">
              {/* Connector line */}
              {i < steps.length - 1 && (
                <div className="hidden lg:block absolute top-8 left-1/2 w-full h-0.5 bg-sage-100 dark:bg-gray-800" />
              )}
              <div className="relative z-10 w-16 h-16 rounded-2xl bg-sage-600 text-white font-display text-2xl font-bold flex items-center justify-center mx-auto mb-4 shadow-lg">
                {s.step}
              </div>
              <h3 className="font-display text-lg font-semibold text-sage-900 dark:text-white mb-2">{s.title}</h3>
              <p className="text-sage-600 dark:text-gray-400 text-sm leading-relaxed">{s.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── PRICING ── */}
      <section className="bg-white dark:bg-gray-900 py-20 border-y border-sage-100 dark:border-gray-800">
        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-8">
            <h2 className="font-display text-4xl font-bold text-sage-900 dark:text-white mb-3">
              Simple, honest pricing
            </h2>
            <p className="text-sage-600 dark:text-gray-400 text-lg mb-4">Start free. Upgrade when you're ready.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-3xl mx-auto stagger-children">
            {plans.map((plan) => (
              <div key={plan.name} className={`card relative ${plan.color} ${plan.popular ? 'scale-105 shadow-xl' : ''}`}>
                {plan.popular && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-amber-400 text-white text-xs font-bold px-4 py-1 rounded-full shadow">
                    <span className="inline-flex items-center gap-1">
                      <Star className="h-3.5 w-3.5" aria-hidden="true" />
                      Most Popular
                    </span>
                  </div>
                )}
                <div className="mb-4">
                  <span className={`${plan.popular ? 'badge-premium' : 'badge-free'} inline-flex items-center gap-1.5`}>
                    <plan.badgeIcon className="h-3.5 w-3.5" aria-hidden="true" />
                    {plan.badge}
                  </span>
                  <div className="mt-3">
                    <span className="font-display text-4xl font-bold text-sage-900 dark:text-white">
                      {plan.price}
                    </span>
                    <span className="text-sage-500 dark:text-gray-400 ml-1 text-sm">/{plan.period}</span>
                  </div>
                </div>
                <ul className="space-y-2 mb-6">
                  {plan.features.map((f) => (
                    <li key={f} className="flex items-center gap-2 text-sm text-sage-700 dark:text-gray-300">
                      <Check className="h-3.5 w-3.5 text-sage-500 dark:text-sage-400 flex-shrink-0" aria-hidden="true" />
                      {f}
                    </li>
                  ))}
                </ul>
                <Link to={plan.to} className={plan.ctaStyle}>
                  {plan.cta}
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ── */}
      <section className="py-20 max-w-6xl mx-auto px-4 text-center">
        <div className="bg-gradient-to-br from-sage-600 to-sage-700 rounded-3xl p-12 text-white relative overflow-hidden">
          <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(circle at 20% 50%, white 0%, transparent 50%), radial-gradient(circle at 80% 50%, white 0%, transparent 50%)' }} />
          <div className="relative z-10">
            <div className="mx-auto mb-5 flex justify-center">
              <BrandLogo size="lg" className="h-[14.0625rem] w-[14.0625rem]" />
            </div>
            <h2 className="font-display text-4xl font-bold mb-4">Ready to eat heAlthy?</h2>
            <p className="text-sage-200 text-lg mb-8 max-w-xl mx-auto">
              Join thousands of people achieving their health goals with AI-powered nutrition planning.
            </p>
            <Link
              to="/register"
              className="inline-flex items-center gap-2 bg-white text-sage-700 dark:text-gray-200 hover:bg-sage-50 dark:bg-gray-800 font-semibold text-lg px-8 py-4 rounded-2xl transition-all duration-200 shadow-lg hover:shadow-xl hover:scale-105"
            >
              <ArrowRight className="h-5 w-5" aria-hidden="true" />
              Get Started — It's Free
            </Link>
            <p className="text-sage-300 text-sm mt-4">No credit card · No expiry · Free forever</p>
          </div>
        </div>
      </section>

      {/* ── FOOTER ── */}
      <footer className="border-t border-sage-100 dark:border-gray-800 py-8 text-center">
        <div className="flex items-center justify-center gap-2 mb-2">
          <BrandLogo size="sm" className="h-[6.4453125rem] w-[6.4453125rem]" />
          <span className="font-display text-xl font-semibold text-sage-900 dark:text-white">heAlthy</span>
        </div>
        <p className="text-sage-400 dark:text-gray-500 text-sm">
          <span className="inline-flex items-center gap-1.5">
            Made with
            <Heart className="h-3.5 w-3.5" aria-hidden="true" />
            as a student final project · Powered by Groq AI & Open Food Facts
          </span>
        </p>
      </footer>
    </div>
  );
}
